name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t package/
        cd package
        zip -r ../lambda_function.zip .
        cd ..
        zip -g lambda_function.zip lambda_function.py

    - name: Upload Lambda function package
      uses: actions/upload-artifact@v2
      with:
        name: lambda_function_package
        path: lambda_function.zip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Apply Terraform
      run: |
        terraform init
        terraform apply -auto-approve
